### ISSUE TITLE
Removing the step of adding the avatar during the user creation

### ISSUE THREAD

**Issue by HostFat** [StampChat/stamp#118]
Maybe it is good to remove the need of adding the avatar on the creation of the account, just to remove another step.

If you really want to push the user to add an avatar, it can be good to add a little warning, like: "You didn't set the avatar, do you want to continue anyway? (you can add it later) [YES / NO]

**Comment by hlb8122** [comment]
I think this could be fixed by simply not adding the avatar, and then a missing avatar is assumed to be the default avatar client side. At the moment if the avatar is missing during sign-up it'll just blow up.
