### ISSUE TITLE
trying to reconnect to relay server doesn't seem to work

### ISSUE THREAD

**Issue by rawb0t** [StampChat/stamp#233]
i accidentally unplugged my network cable and after plugging it back in, i'd try to "retry" connecting and it would try for a few moments then tell me again it had lost connection and ask me to retry again. only way to reconnect was to restart stamp entirely

i didnt try to debug it further than that. sorry.

**Comment by schancel** [comment]
Yeah, the relay stuff probably doesn't reconnect smoothly. On the other hand, it doesn't disconnect often.
