### ISSUE TITLE
Keyboard automatically hides after sending a message

### ISSUE THREAD

**Issue by nghiacc** [StampChat/stamp#390]
I am experiencing quite an annoying UI issue, when a message is sent, the keyboard automatically hides. This leads to some annoying behavior:
- The new message will not be displayed on the screen, instead the last one is visible.
- As a result, when the user focuses on the chat prompt, the latest messages does not show up, the screen does not scroll to the latest ones.

These needs to be fixed. Proposed fixes:
- After sending a message, the keyboard should stay visible, so that the user can type again
- The latest message should be showing up to the chat windows after sending.

**Comment by schancel** [comment]
Fixed! Thanks guys!
