### ISSUE TITLE
Bug: Settings ("Dark Mode") not persisted

### ISSUE THREAD

**Issue by sondreb** [StampChat/stamp#404]
I changed to "Dark Mode" in settings on first launch and setup, when I fully exit Stamp and open again, it renders in "Light Mode".

**Comment by schancel** [comment]
@wiktorcie Is this an issue for you?

**Comment by wiktorcie** [comment]
Which build is this about? Windows / Mac / PWA? I checked on electron-ubuntu and it works there as intended.

**Comment by schancel** [comment]
Should be fixed now.
