### ISSUE TITLE
Balance Doubles when user presses back and then proceed when creating an account

### ISSUE THREAD

**Issue by ajugorji** [StampChat/stamp#407]
1. Created a new stamp character
2. Received some Lotus from the Faucet.
3. Upon reading the "Do not forget your character's secret name, you will never be able to remember them again." click back to make sure the seed is saved
4. Click proceed again
5. The balance will have doubled.

If back and proceed is clicked again the balance will increase again. This balance issue then proceeds to the stamp messaging home screen. 

![Amount received from the faucet](https://user-images.githubusercontent.com/775440/134264974-533d1470-69a1-4952-93f3-9375115074bc.png)
![Doubling](https://user-images.githubusercontent.com/775440/134264969-69182a30-6c56-4e95-b1b6-d68a149e09db.png)
![Doubling Again](https://user-images.githubusercontent.com/775440/134264963-39d64478-991b-4c59-a4c2-1a97bcd69868.png)
![Stamp Balance Issue Messaging Screen](https://user-images.githubusercontent.com/775440/134264971-a93218f7-6bb8-47b3-84c8-75ec7822ccd4.png)

**Comment by schancel** [comment]
Has been fixed. Thank you.
