### ISSUE TITLE
Scoll down button not working on click

### ISSUE THREAD

**Issue by schancel** [StampChat/stamp#471]
<img width="57" alt="image" src="https://user-images.githubusercontent.com/213740/141152699-3aa9fead-be94-4e6b-bece-6cc16962fca6.png">

This button does not seem to be working anymore. Unclear why.

**Comment by maff1989** [comment]
should be fixed by https://github.com/StampChat/stamp/pull/530

ref. Chat.vue "buttonScrollBottom" method
