### ISSUE TITLE
Price endpoint for automatically adjusting offerings

### ISSUE THREAD

**Issue by schancel** [StampChat/stamp#612]
In order to stabilize coin prices without a formal peg, we want to adjust offering rates to be in line with USD prices. This will have the effect of burning more or less coins inverse to the current price of XPI and help stabilize the price.

**Comment by maff1989** [comment]
Price in USDT can be polled at: https://explorer.givelotus.org/ext/getlastprice/exbitron

Output:
```
{"usdt":0.000112}
```
